const ADD_ITEM = 'ADD_ITEM';
const REMOVE_ITEM = 'REMOVE_ITEM'
const ADD_SHOPPINGCART = 'ADD_SHOPPINGCART'
const REMOVE_SHOPPINGCART = 'REMOVE_SHOPPINGCART'
const LOGIN_USER = 'LOGIN_USER'
const LOGOUT_USER = 'LOGOUT_USER'

export { ADD_ITEM, REMOVE_ITEM, LOGIN_USER, LOGOUT_USER, ADD_SHOPPINGCART, REMOVE_SHOPPINGCART };